### ISSUE TITLE
Search Freezes

### ISSUE THREAD

**Issue by bitboxer** [mileszs/ack.vim#13]
Sometimes the search freezes and freezes the complete macvim window. Sadly I can't reproduce it but I think it has something to do with the NerdTree. Everytime the search freezes, NerdTree was open.

**Comment by lucascaton** [comment]
7 years later and the same issue still happens ¯\_(ツ)_/¯

**Comment by ches** [comment]
@lucascaton Sorry to hear that, but there's very little solid reproduction info here so it's kind of difficult to understand the source of the problem.

**Comment by lucascaton** [comment]
@ches I totally understand. I wasn't complaining, just reporting it still happens sometimes.
I wish I could help to fix it. Thanks anyway. BTW, sometimes a ctrl+c solves it 😄
