### ISSUE TITLE
g:ack_default_options only applied if g:ackprg 

### ISSUE THREAD

**Issue by Konfekt** [mileszs/ack.vim#139]
In documentation, note that g:ack_default_options only applied if g:ackprg unset!

Thanks to 
```
if !exists("g:ackprg")
  if executable('ack')
    let g:ackprg = "ack"
  elseif executable('ack-grep')
    let g:ackprg = "ack-grep"
  else
    finish
  endif
  let g:ackprg .= g:ack_default_options
endif
```
the g:ack_default_options are only applied if g:ackprg is unset.

Either
- note this in the documentation (and explain that the options can be passed directly to `g:ackprg`), or
- apply these options even if `g:ack_default_options` is set.

**Comment by ches** [comment]
#152 will resolve this, if that pull request doesn't get rebased soon then I'll address it myself. So I'm going to close this issue in favor of that issue/PR, but I'd like to understand use cases for having both `g:ackprg` and `g:ack_default_options` exist—if you could please comment on #152 about how you use them I'd appreciate it!
