### ISSUE TITLE
relative path vs absolute path

### ISSUE THREAD

**Issue by alexandnpu** [mileszs/ack.vim#143]
when using regex in the search pattern, there is mix of relative paths and absolute paths in the result output.
But ack outside vim works fine.

I am using ack 2.12.

**Comment by ches** [comment]
Whenever you observe this happening, could you check `:ls` and see how your already-open buffers appear to Vim? It's unclear to me that this is a problem specific to ack.vim, but maybe we can take some steps to mitigate problems, similar to [this].

[this]: https://github.com/mileszs/ack.vim/blob/f04a8a9af3854f9fd97318e05a0e5e05281da33f/autoload/ack.vim#L77

**Comment by Numkil** [comment]
I've also noticed this behaviour when just setting grep variables to ag/ack without the use of a plug-in. So I don't think the problem lies in the plugin but rather in vim itself.

**Comment by cyboflash** [comment]
I'm having the same problem. [Here] (http://vi.stackexchange.com/questions/4815/uneven-quickfix-window-output-from-ack-ag) is where I describe the issue in more detail. [The first comment of the answer] (http://vi.stackexchange.com/questions/4815/uneven-quickfix-window-output-from-ack-ag#comment7330_4816) contains the suggested solution. Is it possible to implement this in the plugin?

**Comment by Numkil** [comment]
@cyboflash 
Are you talking about this command?
```vimscript
au BufAdd * exe "cd" fnameescape(getcwd())
```
It doesn't seem to do anything other than changing to directories for me without any side effects.

**Comment by cyboflash** [comment]
@Numkil 

    au BufAdd * exe "cd" fnameescape(getcwd())

It worked for me. I'm using it as a temporary solution. The suggestion I was talking about is [here](http://vi.stackexchange.com/questions/4815/uneven-quickfix-window-output-from-ack-ag#comment7330_4816)

**Comment by Numkil** [comment]
I'm sorry it does seem to work for me as well, forgot vim and neovim use seperate *vimrc's. I will look into the viability of this if I get some free time in the weekend and I'll thumbs up here to support your solution if it works without being intrusive.

**Comment by ches** [comment]
Thanks for sharing the workaround. I'd agree with @Numkil that since it's a general quirk of Vim, it's not ack.vim's place to fix/work around it, especially since that solution does make major assumptions about the users' workflow, as its author noted.

I'll leave this issue open for now as a form of documentation. If anyone would like to add a note about this to ack.vim's help doc file including the suggested workaround with caveats acknowledged, I'd welcome a PR for that!

**Comment by skywind3000** [comment]
a patch for this is ready:

https://github.com/vim/vim/issues/2846
