### ISSUE TITLE
ack with ag cannot use the ~/.agignore file

### ISSUE THREAD

**Issue by jinleileiking** [mileszs/ack.vim#145]
in vim,
use ack.vim with ag to search some text.
the ag command cannot use the ~/.agignore file to ignore files .

**Comment by ches** [comment]
I use ag with ack.vim and I've just verified that my `~/.agignore` entries do filter results when run from ack.vim, as expected.

Closing due to lack of response, please open a new issue if you have a reproducible example where searching within Vim gives different results than command-line ag.
