### ISSUE TITLE
The manual download link in README.md does not work

### ISSUE THREAD

**Issue by timrau** [mileszs/ack.vim#148]
$ wget https://github.com/mileszs/ack.vim/archive/kb-improve-readme.zip
    --2014-11-27 11:31:59--  https://github.com/mileszs/ack.vim/archive/kb-improve-readme.zip
    Resolving github.com (github.com)... 192.30.252.131
    Connecting to github.com (github.com)|192.30.252.131|:443... connected.
    HTTP request sent, awaiting response... 302 Found
    Location: https://codeload.github.com/mileszs/ack.vim/zip/kb-improve-readme [following]
    --2014-11-27 11:32:00--  https://codeload.github.com/mileszs/ack.vim/zip/kb-improve-readme
    Resolving codeload.github.com (codeload.github.com)... 192.30.252.147
    Connecting to codeload.github.com (codeload.github.com)|192.30.252.147|:443... connected.
    HTTP request sent, awaiting response... 404 Not Found
    2014-11-27 11:32:01 ERROR 404: Not Found.

Clicking directly on the link get a page showing `Not Found` too.

**Comment by ches** [comment]
Closed via b6fb459822f13. Thanks @Happy-Dude!
