### ISSUE TITLE
Keeps activating new window with first file from search results

### ISSUE THREAD

**Issue by zatan** [mileszs/ack.vim#153]
Hi,

I am having issue with ack.vim its keeps activating new window with first search result its only happens if I change current working directory for example `cd /var/www/` than `ack 'foo'` window gets open with first search result that's not happening if I don't change current working directory.

If you need more info please let me know.

**Comment by ches** [comment]
Could you give an example with the explicit sequence of steps and Vim commands that you're running to exhibit the problem? And any config values you've set for ack.vim?

You are using the `:Ack!` bang form of the plugins commands and not plain `:Ack`, right?

**Comment by zatan** [comment]
Thank using `:Ack!` solved a problem.

Cheers

**Comment by ches** [comment]
Glad it was that simple :grin:
