### ISSUE TITLE
E117 unknown function

### ISSUE THREAD

**Issue by Kensuke-Hinata** [mileszs/ack.vim#160]
I stored ack.vim under ~/.vim/plugin and got E117 unknown function ack#Ack.

**Comment by ches** [comment]
Is the rest of the plugin installed, like `~/.vim/autoload/ack.vim`? If you install manually then you should `cd ~/.vim` and then `unzip /path/to/downloaded/archive.zip`.

**Comment by Kensuke-Hinata** [comment]
well, I got the reason, the problem was solved after I added directory "autoload" under ~/.vim...
