### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by juanibiapina** [mileszs/ack.vim#162]
Would you consider shortcuts like these?: https://github.com/teoljungberg/vim-grep/blob/master/plugin/grep_motion.vim

So you can do "grw" to grep for a word.

**Comment by ches** [comment]
Hi,

Sorry that this issue went without a response for so long. Trying to clean house a little bit now.

I think the ability to use text objects is nifty, but I'm personally not really big on plugins adding a lot of mappings by default, and this type in particular is potentially pretty invasive/surprising.

The example you gave of `grw` seems like what I'd use by far the most often, and ack.vim supports that use case fairly conveniently by automatically using `<cword>` if you `:Ack` with no query given.

So I'd rather not maintain this as a core feature in the plugin, but if you want to create a "tips" or "cookbook" wiki page and show mappings/functions to do this with ack.vim there, that'd be cool!
