### ISSUE TITLE
Error detected while processing function ack#Ack..<SNR>94_SearchWithGrep

### ISSUE THREAD

**Issue by romanblanco** [mileszs/ack.vim#164]
Happens to me that when for some searches, vim is throwing errors. For example:

`vim +Ack\ "cfme_dynatree_node_remove_class"` throws error:

    Error detected while processing function ack#Ack..<SNR>94_SearchWithGrep:
    line    9:
    E325: ATTENTION
    Error detected while processing function ack#Ack:
    line   27:
    E171: Missing :endif
    Press ENTER or type command to continue

If I use `ag` for search in terminal, I got 

    *[master][~/devel/manageiq/app]$ ag "cfme_dynatree_node_remove_class"
    assets/javascripts/miq_dynatree.js
    144:function cfme_dynatree_node_remove_class(treename, key) {

Usually this works fine to me. This occurs only in some cases.
I'm using ack.vim with `ag`: `let g:ackprg = 'ag --nogroup --column`.

**Comment by jergason** [comment]
I have this issue as well, but it is pretty intermittent.

The output I see in vim looks like this:

```
Error detected while processing function ack#Ack..<SNR>115_SearchWithGrep: line 8: E325: ATTENTION Error detected while processing function ack#Ack: line 27: E171: Missing :endif
```

**Comment by ches** [comment]
Doh, hopefully that silly little change takes care of it :wink:

**Comment by jdhao** [comment]
@ches ,
I am using latest version of ack with ag. I have also met this issue. The error only occurs for some search. 

```
let g:ackprg = 'ag --vimgrep'
```

How to deal with this issue?
