### ISSUE TITLE
Adding a LICENSE file at the root of the project

### ISSUE THREAD

**Issue by Spredzy** [mileszs/ack.vim#172]
Hello,

I am currently packaging ack.vim for integration within Fedora. As part of our Guideline[1], a project should have its license file at its root. In the code it is clearly specified that ack.vim follows the same license that Vim itself[2], but would it be possible to have a copy of the license[3] directly at the root also?

Thanks in advance,

[1] https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Text
[2] https://github.com/mileszs/ack.vim/blob/master/doc/ack.txt#L5
[3] http://vimdoc.sourceforge.net/htmldoc/uganda.html

**Comment by ches** [comment]
Thanks for your interest in packaging the plugin @Spredzy! Please let me know if there's anything more following the above referenced commit.

**Comment by Spredzy** [comment]
Thank you @ches will let you know.

**Comment by ches** [comment]
Also I just tagged a release with that commit, so that might help :smile:

**Comment by Spredzy** [comment]
It does, I'll package 1.0.9 instead of 1.0.8 ;) Thanks much appreciated.
