### ISSUE TITLE
nobuflisted for preview

### ISSUE THREAD

**Issue by samuelsimoes** [mileszs/ack.vim#174]
Hi people,

There's some way to show the previews (mapping `go`) with the `nobuflisted` setted? When you are searching something and you use the buffer list to your workflow the buffer list gets cluttered with the many files opened for the preview. :disappointed: 

Thanks for your attention.

**Comment by samuelsimoes** [comment]
With custom mapping I got it :smiley: 
```
let g:ack_mappings = { "go": ":.cc <bar> setlocal nobuflisted<CR><C-W>j" }
```

**Comment by ches** [comment]
Thanks for sharing the mapping solution @samuelsimoes, I think this is a good idea in general and I'd consider including it as a standard feature. I'm not sure I'll have much time for it soon, but I'd certainly entertain a pull request to add it (it'd be nice to do it in a way that isn't just based on mappings, I already think ack.vim's mapping configuration approach is rather clumsy and I'd rather provide `<Plug>` mappings if I can ever get around to such a major change…).
