### ISSUE TITLE
Search results leak into terminal

### ISSUE THREAD

**Issue by jerodsanto** [mileszs/ack.vim#18]
When I run vim from OS X's (10.6.7) Terminal or iTerm apps and use the `Ack` command it works as expected, but upon closing vim all of the search results have been printed in the terminal window.

This does not occur when using MacVim even if it is launched via the `mvim` command.

**Comment by ekouters** [comment]
This is still an issue for me.
@kassio suggests changing vim's default behavior, but this is no option for me.
@lesguillemets links to an issue which was solved with a commit that worked for me. Thanks!

**Comment by sfahlberg** [comment]
@Kagami that worked for me- thanks!

**Comment by skamsie** [comment]
I just installed the plugin and I notice I actually have this problem. Using vim on mac

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb  6 2017 06:58:22)
MacOS X (unix) version
Included patches: 1-311
Compiled by Homebrew
```

**Comment by mcadam** [comment]
Same issue for me with vim 8 on mac

**Comment by mcadam** [comment]
@skamsie Just added that `set shellpipe=>` to my .vimrc and fixed it in the meantime.

**Comment by yevhen-m** [comment]
I have this issue as well, output is printed on the screen and distracts a lot. `set shellpipe=>` fixes this indeed. Is it the best way to solve this issue?

**Comment by jonathankau** [comment]
Adding `set shellpipe=>` does fix the issue, but it also blocks shell output from other plugins (like fugitive).

I ended up writing a Vimscript function that takes in the search param and makes sure to set/unset shellpipe properly:

```
function! Search(string)
  set shellpipe=>
  execute "Ack! \"" . a:string . "\""
  set shellpipe=2>&1\|tee
endfunction
nnoremap <C-F> :call Search("")<left><left>
```

**Comment by ZyX-I** [comment]
@jonathankau This can hardly be considered “properly”. Correct variant is using 1. original `&shellpipe` value and not anything hardcoded, 2. `finally` and 3. `shelleescape()`:

```VimL
function Search(string) abort
  let saved_shellpipe = &shellpipe
  let &shellpipe = '>'
  try
    execute 'Ack!' shellescape(a:string, 1)
  finally
    let &shellpipe = saved_shellpipe
  endtry
endfunction
```

. Note though that I may be incorrect regarding escaping here though: it is definitely correct variant for `ag.vim`, but I am no longer using `ack.vim`.

**Comment by lovesora** [comment]
@jonathankau Thank you! It works.
