### ISSUE TITLE
Neovim async job control

### ISSUE THREAD

**Issue by zegervdv** [mileszs/ack.vim#187]
Is there any work being done to make Ack work asynchronously using the job control features in neovim? I know there is dispatch support (#19), but we could use the native functionality of neovim.

I've been trying this out and can send a provisional pull request. Only the basic Ack works for now, and things can most likely be improved.

**Comment by ches** [comment]
This isn't something I've done any work on, if it can be implemented in a way that has mostly consistent behavior between synchronous/asynchronous and for non-Neovim users, I'd be happy to consider it.

The existing Dispatch support for instance does have some caveats, see the links on #167 for example. I think a more seamless experience should be possible with Neovim.

A few people did some work on rking/ag.vim#85 that you might be able to reference, and vim-grepper also has some async support.

**Comment by ches** [comment]
Also relates to #209.
