### ISSUE TITLE
Perm Ack with directory as the directory of the current open buffer

### ISSUE THREAD

**Issue by zedan185** [mileszs/ack.vim#192]
I would like to perform Ack with directory as the directory of the current open buffer or a buffer that I specify. is there a way for me to see which Dir the Ack command is being applied to ?

**Comment by ches** [comment]
ack.vim uses Vim's notion of `:pwd`, just like `:grep` and `:vimgrep` do. If you prefer to search relative to the current buffer's file all the time, `:set autochdir` should be exactly what you wish. This does sometimes have side effects you may not like though (some plugins might not work well with `autochdir`). In that case you could check out #26 or #188 for some ideas.

For sometimes specifying a search path, you can just give it as a third argument to an `:Ack` command, e.g. `:Ack 'search pattern' src/test/java/`.

Hope this helps.
