### ISSUE TITLE
how to search the current buffer by ack in vim?

### ISSUE THREAD

**Issue by jackywu** [mileszs/ack.vim#194]
how to search the current buffer by ack in vim?

**Comment by ches** [comment]
You can simply append a path to your `:Ack` command to restrict the search. For the current file only this can simply be `%` as per `:help expand()`:

    :Ack search-pattern %

Of course you can make a mapping if this is something you do often, e.g.

    nnoremap <Leader>af :Ack  %<Left><Left>
