### ISSUE TITLE
LAck open result in Quickfix list

### ISSUE THREAD

**Issue by z-jason** [mileszs/ack.vim#196]
I found that if I enable the dispatch feature
```
let g:ack_use_dispatch = 1
```
All the location-list command (e.g. LAck) will open the result in Quickfix list. Is it by designed or is it a bug

**Comment by z-jason** [comment]
`

**Comment by ches** [comment]
Hi, yes this [is a known shortcoming][1] because, last I checked, Dispatch has no support for using location lists.

[1]: https://github.com/mileszs/ack.vim/blob/eede0425f50d92be89ee8fb4560a5afb707c2a54/doc/ack.txt#L75-L78
