### ISSUE TITLE
Add ability to go to next result

### ISSUE THREAD

**Issue by chauncey-garrett** [mileszs/ack.vim#198]
Would be useful to have the ability to got to the next result without having to switch back to the quickfix window to select it.

**Comment by ches** [comment]
It's a standard Vim [quickfix list][1] (or location list if you use `:LAck*`), so you can move through results with `:cn` and `:cp`. I recommend creating mappings for them, you'll get a lot of use of them if you use Syntastic for linters, `:make` or `:Dispatch` for builds, etc. (personally I use media keys on the function row, with Play running builds etc. and RW/FF being `:cprev`/`:cnext` and `:lprev`/`:lnext` when prefixed by leader).

Specific to ack.vim, see also `:help g:ackpreview` and the `go` binding under `:help ack-mappings` in case those are to your liking.

[1]: http://vimdoc.sourceforge.net/htmldoc/quickfix.html

**Comment by chauncey-garrett** [comment]
Thanks @ches!
