### ISSUE TITLE
:Ack errors out... sometimes.

### ISSUE THREAD

**Issue by jpassaro** [mileszs/ack.vim#199]
Unable to figure out exactly when this happens, it is inconsistent. Sometimes `:Ack` works just fine. Other times, I will have a blank screen forever till I press a key, then the following error on the blank screen:

```
Error detected while processing function ack#Ack[41]..<SNR>37_SearchWithGrep:
line    8:
E325: ATTENTION
Error detected while processing function ack#Ack:
line   41:
E171: Missing :endif
```

Then vim displays again but the status window is all screwed up.

Apologies that I cannot advise how to reproduce. Just now as I was typing this, the session in which I encountered the error executed the same `:Ack` command correctly, so this might be tricky to pin down. Suggestions welcome.

**Comment by jpassaro** [comment]
Since installing tpope/vim-dispatch and adding `let g:ack_use_dispatch = 1`, this problem appears to have gone away.

**Comment by MrJadaml** [comment]
I am run into that issue as well. The Tim Pope plugin did not fix it for me.
