### ISSUE TITLE
Remove highlight from first row

### ISSUE THREAD

**Issue by yefim** [mileszs/ack.vim#200]
For some reason, the first row is always entirely highlighted when I search. I've turned off `ackhighlight` and still the first row is highlighted. Is there some setting I'm missing to turn off this highlight?

<img width="1552" alt="screenshot 2016-12-03 23 17 49" src="https://cloud.githubusercontent.com/assets/1170843/20864669/d89c9c52-b9ae-11e6-96e1-433eb9dbd986.png">

**Comment by ches** [comment]
Hi @yefim,

This is common behavior of Vim quickfix lists, it isn't controlled by ack.vim specifically. It's showing the current position for navigating by stack, so if you do `:cnext` you'll see it move down a line.

I'm not sure if it's possible to turn it off through Vim configuration, but if you want to tweak the style to make it less obtrusive, it's [apparently controlled by the `Search` highlight group][1]:

> `Search`: If the default look of search matches looks unsightly to you, you could tweak this as I showed above. Note that this also affects the currently active line in the quickfix window.

So unfortunately toning it down affect would your normal `:highlight` appearance too which might be undesirable (though in that Solarized case I'd say the brightness is pretty obnoxious across the board…).

[1]: http://andrewradev.com/2011/08/06/making-vim-pretty-with-custom-colors/

**Comment by yefim** [comment]
@ches thanks for the great explanation 😄 I ended up going down a few more rabbit holes and [found](http://stackoverflow.com/questions/40707737/cursor-highlighting-in-quickfix-window-quickfixcmdpre-overriding-quickfixcmdpos) that `qf.vim` affects only the quickfix window and then modified my Search highlight there. Also, I [found](http://stackoverflow.com/questions/13220073/vim-highlight-quickfix-selected-line-with-color-different-than-search) a patch to have vim allow you to change the highlighting of that line.

Hopefully, my vim looks much nicer (less obnoxious) now.

<img width="1552" alt="screenshot 2016-12-04 02 16 18" src="https://cloud.githubusercontent.com/assets/1170843/20865462/a9c666ce-b9c7-11e6-9502-1f035ead681e.png">

**Comment by ches** [comment]
Nice find on the patch! Would be nice if that gets upstreamed.

**Comment by yefim** [comment]
Looks like it was upstreamed in Neovim! 🙌  https://neovim.io/doc/user/syntax.html#hl-QuickFixLine
