### ISSUE TITLE
Search highlighted word

### ISSUE THREAD

**Issue by abacha** [mileszs/ack.vim#203]
Is it possible to bind a shortcut (ie _leader_ G) to do :Ag _word_?

**Comment by sdx23** [comment]
I'd like this. Also with a range, so
 1 select smth in visual mode
 2 `:'<,'>Ack`

**Comment by ches** [comment]
Yes, sure, see #33 for an example. The plugin automatically uses the word under the cursor if no search string is given but as shown you can use `<cword>` to make it explicit.

There is no support for ranges currently, that could be a nice contribution.
