### ISSUE TITLE
Any ideas why ack is search all the files? 

### ISSUE THREAD

**Issue by yifanchen** [mileszs/ack.vim#208]
Neovim 0.1.7
Mac Sierra 
fzf 0.16.6
ack 2.14

So, I installed Ack today. When I ran `:Ack`, it searched all my files of the current directory, isn't it supposed to open a window so I can enter search query?

**Comment by ches** [comment]
The default behavior is that if you run `:Ack` with no query, ack.vim will perform a search for the word currently under your cursor (`:help <cword>` and `:help g:ack_use_cword_for_empty_search`).

You are expected to give a query to the command, like `:Ack searchterm [optional subdirectory]`, the plugin doesn't interactively prompt you for a query. Please see `:help ack`.

**Comment by yifanchen** [comment]
I see, thanks.
