### ISSUE TITLE
Different files always open in a new tab

### ISSUE THREAD

**Issue by zhiwei-nu** [mileszs/ack.vim#213]
When opening files, with `o` from the quickfix window, it always opens in a new tab if the file is different. Is this the intended behavior? If not where do I start to look at to fix this?

**Comment by PangPangPangPangPang** [comment]
:h switchbuf

**Comment by ches** [comment]
Yes, as @PangPangPangPangPang suggests my first suspicion would be that you have `set switchbuf=newtab`. If that's not the case feel free to re-open and we can further confirm that there isn't a bug.

**Comment by elkesrio** [comment]
I'm having the same problem, and I have `set switchbuf=useopen`. Do you have any idea about the causes of this problem?

**Comment by tripathyas** [comment]
In my case, switchbuf=useopen,usetab,newtab
Still enter is opening new tab for every file.

**Comment by nighthawk469** [comment]
In my case switchbuf=usetab is set automatically in the config I was using https://github.com/amix/vimrc

Use this in your vimrc to change it back to the default vim setting
```set switchbuf=```
