### ISSUE TITLE
How do I search with a pattern that contains a space?

### ISSUE THREAD

**Issue by rightfold** [mileszs/ack.vim#221]
I tried several things, like `:Ack foo bar src` and `:Ack "foo bar" src` but they don't search for "foo bar" in `src/`. I also can't find it in the documentation. How do I search with a pattern that contains whitespace?

**Comment by benoittgt** [comment]
`:Ack "foo bar" src` should work. Tested only with CLI and it works. If you try with `-Q` do you have the same result?

`  -Q, --literal                 Quote all metacharacters; PATTERN is literal`

**Comment by rightfold** [comment]
I found it: I have to use single quotes: `:Ack 'foo bar' src`

**Comment by JonnyRa** [comment]
maybe this documentation should move the front page?

**Comment by JonnyRa** [comment]
Nice one!
