### ISSUE TITLE
Open search results vertically goes to left most instead of right.

### ISSUE THREAD

**Issue by yujinyuz** [mileszs/ack.vim#241]
I have enabled
```
set splitright
```
on my `~/.vimrc`

But every time I do a search and press `v` to open the file vertically, it goes to the left most pane and not opening a new pane to the right.

Can anyone help me with this?

**Comment by IlyaUmanets** [comment]
@yujinyuz, hey, how did you manage it?

**Comment by Integralist** [comment]
Looks like `s:ack_mappings` will _extend_ the data structure using `g:ack_mappings` if set...

```vim
" help Ack mappings to respect my split settings
let g:ack_mappings = {
  \ "h": "<C-W><CR>:exe 'wincmd ' (&splitbelow ? 'J' : 'K')<CR><C-W>p<C-W>J<C-W>p",
  \ "v": "<C-W><CR>:exe 'wincmd ' (&splitright ? 'L' : 'H')<CR><C-W>p<C-W>J<C-W>p"}
```
