### ISSUE TITLE
Mapping: Auto quotes with under the cursor search

### ISSUE THREAD

**Issue by PezCoder** [mileszs/ack.vim#244]
### What ?
There are two usecases that I commonly use with ack.vim:
1. Searching with a keyword -> This always requires wrapping with single quotes
2. Searching under current word

I went through some iterations to make sure the above two things can be executed as easily as possible.
Putting this here, in case people looking out for something similar might found this helpful.

#### Iteration 1
My earlier config looked something like this:
```vim
nnoremap <Leader>/ :Ack!<Space>

" Commands
" <leader>/ 'search with spaces'<CR> -> Search for the text entered in quotes
" <leader>/<CR> -> Search under the cursor
```

#### Iteration 2
To make sure I don't have to type the quotes every time, I did this: 
Reference: https://github.com/mileszs/ack.vim/issues/140#issuecomment-71561901
```vim
nnoremap <Leader>/ :Ack! ''<left>

" Commands
" <leader>/ search without quotes<CR> -> No need to type quotes now
" <leader>/<CR> -> This command broke as it executes :Ack! '' with empty string & not under cursor now
```

The above made searching for a string easier but I lost the capability of searching under the word quickly like I use to.

#### Final Solution
I solved the above issue by creating a custom function that executes the ack based on the input received from the user. 
```vim
command! -nargs=* Search call InputAwareAckSearch(<q-args>)
nnoremap <Leader>/ :Search<space>

function! InputAwareAckSearch(args)
    if len(a:args) > 0
        " Executes ack by wrapping user input with quotes
        execute ":Ack! '".a:args."'"
    else
        " For no input, executes empty ack, so that word under cursor is searched
        execute ":Ack!"
    endif
endfunction

" Commands
" <leader>/ search without quotes<CR> -> No need to type quotes now
" <leader>/<CR> -> 🔧Fixed, searches under the cursor 
" Win Win.. !
```

#### A question ?
I'm pretty new to vimscript, hence wanted to ask.
Do you think the above approach is good for the problem I mentioned, Is there a better way to do it ?

**Comment by PezCoder** [comment]
Just realised that I lost the capability of specifying the directory in which ack should run.
I think I'll stick with entering quotes myself for now.

**Comment by helloCodeing** [comment]
Thank you, I set it according to your method, search for the word under the cursor is successful. My previous settings are wrong, thank you very much.

**Comment by abnerDest** [comment]
Thank you!, Now i'm using it in my daily work flow
