### ISSUE TITLE
How to search word under cursor?

### ISSUE THREAD

**Issue by regedarek** [mileszs/ack.vim#33]
Is posible to search words by Ack like this?
- cursor position

`Ad.with_*some_scope(:params[:scope])` and press something like `<leader>vv` to search `:Ack with_some_scope`

**Comment by tiborsimon** [comment]
Yep, it works for me too. @lukaszkorecki  very useful shortcut ;)

**Comment by ssaid** [comment]
@lukaszkorecki great tip, thank you very much!
