### ISSUE TITLE
Searches with "#" blow up

### ISSUE THREAD

**Issue by jacquescrocker** [mileszs/ack.vim#5]
I often need to search for strings that begin with "#" when finding id divs in haml/css

However Ack.vim explodes when using:

```
:Ack -Q "#something"
```

error:

```
E194: No alternate file name to substitute for "#"
```

`ack -Q "#something"` works fine from the command line so something in ack.vim is screwing it up

**Comment by Sean-Lan** [comment]
Hi, guys. I just tried that with my MacVim (version 7.4.622), and it seems that only one back slash is enough and when I input three, nothing will find.
