### ISSUE TITLE
Option to not auto-open first match

### ISSUE THREAD

**Issue by pyrat** [mileszs/ack.vim#59]
Hi there,

Is it possible to configure Ack.vim so that it does not auto-open the first file which matches the search term?

Cheers,
Alastair

**Comment by ejoubaud** [comment]
`cabbrev Ack Ack!` just made my life a whole lot easier :)

**Comment by Eimis** [comment]
@ejoubaud thanks!

**Comment by htatche** [comment]
+1

**Comment by ches** [comment]
@htatche I don't understand any further +1 on this, there are good solutions above like mappings or an abbreviation (personally I primarily use `map <Leader>a  :Ack! ''<Left>` FWIW). Vim offers a wealth of native configurability like this that obviates the need for plugins to have a thousand settings variables.

The default behavior is not going to change, because a.) it would not be backwards-compatible and this is long-existing, and b.) it mirrors the behavior of `:grep` and `:grep!` built into Vim, which is a strong precedent and ack.vim thinly wraps it.

**Comment by SamSaffron** [comment]
The reason so many complain about this is cause `Ack` will always open the bottom window even if top one is in focus, that is a maddening default.

**Comment by ches** [comment]
@SamSaffron If anyone who finds it maddening would like to work up a pull request to make `:Ack!` behave more exactly like `:grep!` in that regard—populating but not opening/focusing the quickfix—I'll gladly consider it. This is a pretty small, straightforward, IMHO fairly well-factored and documented Vim plugin to hack on. I may get around to such a change myself eventually, but not in a particular hurry.

Then, people will probably complain that "I run `:Ack!` and it doesn't do anything!", or it creates inconsistencies with ack.vim's mappings getting applied to the results windows. [I have feelings about that][1], but.

    ¯\_(ツ)_/¯

It would be largely a matter of making one function call conditional, aside from the mappings concern… Opening but not focusing the results on `!` is probably a viable compromise, also a change likely to involve about three lines.

[1]: https://github.com/mileszs/ack.vim/issues/170

**Comment by SamSaffron** [comment]
I would love to fix this, but even `:Ggrep` by the demigod @tpope behaves oddly here. 

If you have this configuration:

[split1]
[split2]
[quickfix results]

When you click on "quickfix result", stuff is always opened in [split2] regardless of [split1] being the window that just had focus. So my vim voodoo feeling here is that vim does not make solving this easy.

**Comment by SamSaffron** [comment]
wow ... I never know about QFEnter, this is soooo useful THANKS!

**Comment by ches** [comment]
Pardon the topical diversion for those subscribed to notifications, but I've also been made aware of [vim-qf] as an alternative, it may offer behavior that suits your taste and might compliment ack.vim without conflict, I haven't gotten around to trying it yet.

[vim-qf]: https://github.com/romainl/vim-qf
