### ISSUE TITLE
~/.ackrc ignored

### ISSUE THREAD

**Issue by stabenfeldt** [mileszs/ack.vim#78]
Searching with `:Ack pattern` takes ages compared to searching from the terminal `$ ack pattern`

How can I make ack-vim ignore the files and directories I´ve specified in my ~/.ackrc ?

Cheers,
martins

**Comment by milushov** [comment]
same issue

@latortuga did u find solution?

**Comment by milushov** [comment]
ow, I found issue by myself, it was same as [here](https://github.com/petdance/ack2/issues/553#issuecomment-100469002) lol
