### ISSUE TITLE
Respecting wildignore

### ISSUE THREAD

**Issue by daGrevis** [mileszs/ack.vim#93]
Is it somehow possible for Ack.vim to respect `wildignore`? It would be really useful for me because my `wildignore` has like 20+ directories and it's pain to manually exclude all of them using `--ignore-dir`.

Maybe script that maps Ack to silently call `Ack --ignore-dir=/foo/ --ignore-dir=/bar/ [..]` based on contents of `wildignore`?

**Comment by daqo** [comment]
It seems that wildignore options doesn't work anymore.
