### ISSUE TITLE
Make it work with --group

### ISSUE THREAD

**Issue by npearson72** [mileszs/ack.vim#94]
Any chance to make this work with --group not just --nogroup?

--group looks nicer, more like Sublime text

**Comment by albfan** [comment]
Take a look on its screencast (it's worth to see)

https://github.com/albfan/ag.vim#shell-mimic

It comes from a previous fork for ag (unmaintained now)

So if you find it interesting I can rework that pull request for this plugin.

**Comment by ches** [comment]
@kassio did end up implementing something like this @albfan, `let g:ack_autofold_results = 1`. It does have a valid problem though (#138) that I would like to address but just haven't taken the time yet, I don't use this feature myself.

I just shared my feelings about significant new features on an ag.vim thread that you're part of, but this is an existing feature so if you feel there are improvements in your implementation, I'm happy to review a pull request bringing the improvements to ack.vim (I haven't looked at your impl yet, but a workaround like the one Konfect suggested on #138 seems perfectly reasonable to me if you've already done something like it).

**Comment by albfan** [comment]
That's a good start point. Fixing something will help to understand codebase. I'll work on it and see what can be done.

I'm agree with "less is more" so let's keep this as simple and lightweight as possible, and discuss on new PR worth of new features.
